genres = ['romance', 'history', 'crime', 'horror', 'music', 'lgbtq+', 'thriller', 'fantasy', 'adventure', 'drama', 'animation', 'musical', 'documentary', 'action', 'sci-fi', 'mystery', 'sport', 'biopic', 'family']

movies = [[['romance', 'drama'], "The Notebook", "Nick Cassavetes", 2004],
          [['horror', 'thriller'], "Halloween", "John Carpenter", 1978],
          [['animation', 'family', 'adventure'], "Spirited Away", "Hayao Miyazaki", 2001],
          [['animation', 'family'], "Zootopia", "Byron Howard & Rich Moore", 2016],
          [['action', 'crime'], "The Beekeeper", "David Ayer", 2024],
          [['musical', 'drama'], "The Wiz", "Sidney Lument", 1978],
          [['documentary'], "Our Father", "Lucie Jourdan", 2022],
          [['drama', 'comedy'], "The First Wives Club", "Hugh Wilson", 1996],
          [['drama', 'comedy', 'mystery'], "Clue", "Jonathan Lynn", 1985],
          [['sci-fi', 'action'], "Everything Everywhere All at Once", "Daniel Kwan & Daniel Scheinert", 2022],
          [['horror', 'mystery', 'thriller', 'fantasy'], "Sleepy Hollow", "Tim Burton", 1999],
          [['action', 'sci-fi'], "Black Panther", "Ryan Coogler", 2018],
          [['comedy', 'drama'], "The Breakfast Club", "John Hughes", 1985],
          [['musical', 'romance', 'comedy'], "Grease", "Randal Kleiser", 1978],
          [['comedy', 'romance'], "Crazy Rich Asians", "Jon M. Chu", 2018],
          [['sci-fi', 'fantasy', 'adventure'], "Star Wars: Episode IV - A New Hope", "George Lucas", 1977],
          [['documentary', 'history'], "Nailed It", "Adele Pham", 2018],
          [['action', 'comedy', 'fantasy', 'adventure'], "Ghostbusters", "Paul Feig", 2016],
          [['documentary', 'history'], "Black Art: In the Absence of Light", "Sam Pollard", 2021],
          [['documentary'], "Won't You Be My Neighbor", "Morgan Neville", 2018],
          [['horror', 'mystery', 'drama', 'crime'], "Split", "M. Night Shyamalan", 2016],
          [['mystery', 'drama', 'crime', 'thriller', 'history'], "Murder on the Orient Express", "Sidney Lumet", 1974],
          [['mystery', 'drama', 'horror', 'crime', 'thriller', 'history'], "A Haunting in Venice", "Kenneth Branagh", 2023],
          [['musical', 'drama', 'family'], "Lyle, Lyle Crocodile", "Josh Gordon & Will Speck", 2022],
          [['action', 'sci-fi'], "The Matrix", "Lana Wachowski & Lily Wachowski", 1999],
          [['sport', 'drama'], "We are Marshall", "McG", 2006],
          [['sport', 'drama', 'biopic'], "42", "Brian Helgeland", 2013],
          [['biopic', 'romance', 'drama'], "Frida", "Julie Taymor", 2002],
          [['animation', 'musical', 'comedy', 'mystery'], "The Bob's Burger Movie", "Loren Bouchard & Bernard Derriman", 2022],
          [['sports', 'action'], "Rocky", "John G. Avildsen", 1976],
          [['comedy', 'family'], "Hocus Pocus", "Kenny Ortega", 1993],
          [['animation', 'family', 'comedy'], 'How the Grinch Stole Christmas', "Chuck Jones & Ben Washam", 1966],
          [['animation', 'family', 'comedy'], "The Grinch", "Scott Mosier & Yarrow Cheney", 2018],
          [['musical', 'romance', 'drama'], "West Side Story", "Jerome Robbins & Robert Wise", 1961],
          [['drama', 'fantasy', 'adventure'], "The Green Knight", "David Lowery", 2021],
          [['adventure', 'fantasy', 'comedy', 'family'], "Jumanji", "Joe Johnston", 1995],
          [['family', 'sport', 'animation', 'comedy'], "Space Jam", "Joe Pytka", 1996],
          [['animation', 'adventure', 'comedy'], "Who Framed Roger Rabbit", "Robert Zemeckis", 1988],
          [['musical', 'comedy', 'romance'], "Singin' in the Rain", "Gene Kelly & Stanley Donen", 1952],
          [['mystery', 'drama', 'thriller'], "Parasite", "Bong Joon-ho", 2019],
          [['action', 'horror', 'thriller'], "Train to Busan", "Yeon Sang-ho", 2016],
          [['documentary'], "Bombshell: The Hedy Lamarr Story", "Alexandra Dean", 2017],
          [['thriller', 'mystery', 'drama', 'crime'], "The Little Things", "John Lee Hancock", 2021],
          [['drama'], "A Raisin in the Sun", "Daniel Petrie", 1961],
          [['horror', 'thriller'], "Night of the Living Dead", "George A. Romero", 1968],
          [['action', 'comedy', 'fantasy', 'adventure'], "Ghostbusters", "Ivan Reitman", 1984],
          [['romance', 'drama'], "Call Me by Your Name", "Luca Guadagnino", 2018],
          [['adventure', 'drama', 'fantasy'], "Life of Pi", "Ang Lee", 2012],
          [['adventure', 'action', 'fantasy'], "The Mummy", "Stephen Sommers", 1999],
          [['family', 'comedy', 'animation', 'adventure'], "Minions: The Rise of Gru", "Kyle Balda", 2022],
          [['mystery', 'thriller', 'comedy', 'crime', 'drama'], "Knives Out", "Rian Johnson", 2019],
          [['musical', 'romance', 'family', 'drama', 'history'], "The Sound of Music", "Robert Wise", 1965],
          [['musical', 'family', 'comedy', 'fantasy'], "Mary Poppins", "Robert Stevenson", 1964],
          [['comedy', 'adventure'], "Joy Ride", "Adele Lim", 2023],
          [['comedy', 'adventure'], "Girls Trip", "Malcom D. Lee", 2017],
          [['biopic', 'music', 'drama', 'lgbtq+'], "Bohemian Rhapsody", "Bryan Singer & Dexter Fletcher", 2018],
          [['biopic', 'drama', 'lgbtq+'], "Milk", "Gus Van Sant", 2008],
          [['drama'], "Eve's Bayou", "Kasi Lemmons", 1997],
          [['horror', 'thriller'], "Candyman", "Bernard Rose", 1992],
          [['drama'], "The Joy Luck Club", "Wayne Wang", 1993],
          [['biopic', 'drama', 'music'], "Selena", "Gregory Nava", 1997],
          [['comedy'], "The Addams Family", "Barry Sonenfeld", 1991],
          [['documentary', 'lgbtq+'], "The Death and Life of Marsha P. Johnson", "David France", 2017],
          [['animation', 'family', 'adventure', 'comedy'], "The Super Mario Bros. Movie", "Aaron Horvath & Michael Jelenic", 2023],
          [['fantasy', 'comedy', 'action', 'adventure', 'drama'], "The School for Good and Evil", "Paul Feig", 2022],
          [['drama'], "Origin", "Ava DuVernay", 2023],
          [['action', 'adventure'], "Crouching Tiger, Hidden Dragon", "Ang Lee", 2000],
          [['action', 'crime', 'drama'], "Romeo Mush Die", "Andrzej Bartkowiak", 2000],
          [['biopic', 'music', 'drama'], "Bob Marley: One Love", "Reinaldo Marcus Green", 2024],
          [['horror', 'thriller', 'mystery'], "Get Out", "Jordan Peele", 2017],
          [['horror', 'thriller', 'drama', 'mystery'], "Bulbbul", "Anvita Dutt Guptan", 2020],
          [['drama', 'lgbtq+', 'history'], "Dance of the 41", "David Pablos", 2020],
          [['documentary'], "Bruce Lee: The Man and the Legend", "Shih Wu", 1978],
          [['action', 'thriller', 'crime', 'drama'], "The Villainess", "Jung Byung-gil", 2017],
          [['horror', 'mystery', 'drama', 'thriller'], "Kindred", "Joe Marcantonio", 2020],
          [['documentary'], "Aftershock", "Paula Eiselt & Tonya Lewis Lee", 2022],
          [['biopic', 'drama', 'music', 'history'], "Chevalier", "Stephen Williams", 2023],
          [['comedy', 'mystery', 'history', 'crime', 'drama'], "Amsterdam", "David O. Russell", 2022],
          [['musical', 'drama', 'history'], "The Greatest Showman", "Michael Gracey", 2017]]